# Use postgres/example user/password credentials
version: '3.8'

services:
  bored_api:
    build: .
    env_file:
      - ./.env
    restart: 'no'
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PORT: ${DB_PORT}
    restart: "on-failure"

volumes:
  postgres_data: