# Use postgres/example user/password credentials
version: '3.8'

services:
  api:
    build: .
    env_file:
      - ./.env
    restart: "on-failure"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PORT=${DB_PORT}
    restart: "on-failure"

volumes:
  postgres_data: